[package]
name = "isar"
version = "0.0.0"
authors = ["Simon Choi <simonleier@gmail.com>"]
edition = "2021"

[dependencies]
isar-core = { path = "../isar_core" }
once_cell = "1.10.0"
serde = "1.0"
serde_json = "1.0"
itertools = "0.10.3"

[lib]
crate-type=["staticlib", "cdylib"]

[features]
default = ["sqlcipher", "native"]
native = ["isar-core/native"]
sqlite = ["isar-core/sqlite"]
sqlcipher = ["sqlite", "isar-core/sqlcipher"]
sqlcipher-vendored = ["sqlcipher", "isar-core/sqlcipher-vendored"]