include: package:lints/recommended.yaml

analyzer:
  # strong-mode:
  #   implicit-casts: false
  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"

linter:
  rules:
    - avoid_private_typedef_functions
    - directives_ordering
    - prefer_single_quotes
