include: package:lints/recommended.yaml
analyzer:
  errors:
    unnecessary_brace_in_string_interps: ignore
    todo: ignore
    unnecessary_string_interpolations: ignore
  exclude:
    - dev/
    - test/
    - test
    - dev
    - templates
linter:
  rules:
    - require_trailing_commas
    - always_declare_return_types
