include: package:flutter_lints/flutter.yaml

analyzer:
  # strong-mode:
  #   implicit-casts: false
  errors:
    avoid_print: ignore
  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"

  language:
    strict-casts: true

  errors:
    avoid_print: ignore
