name: isar_inspector
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.6.0 <4.0.0"
 
dependencies:
  isar:
    path: ../isar
  
  flutter:
    sdk: 'flutter'
  flutter_svg: '^2.0.7' 
  vm_service: '^14.3.1' 
  web_socket_channel: '^2.4.0'
  file_picker: '^9.0.2'
  isar_flutter_libs:
    path: '../../packages/isar_flutter_libs'
dev_dependencies:
  build_runner: 'any'
  flutter_lints: '^5.0.0'

flutter:
  uses-material-design: true

  assets:
    - assets/logo.png
