name: Build Inspector

on:
  push:
    tags:
      - '*'

jobs:
  build_and_upload_macos:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v1
    - uses: subosito/flutter-action@v1
      with:
        channel: 'stable'
    - name: Build
      working-directory: packages/isar_inspector
      run: |
        flutter config --enable-macos-desktop
        flutter build macos
    - name: Compress
      working-directory: packages/isar_inspector/build/macos/Build/Products/Release/
      run: zip -r -y inspector.zip "Isar Inspector.app"
    - name: Upload binary
      uses: svenstaro/upload-release-action@v1-release
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: packages/isar_inspector/build/macos/Build/Products/Release/inspector.zip
        asset_name: Isar Inspector MacOS.zip
        tag: ${{ github.ref }}

  build_and_upload_linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: subosito/flutter-action@v1
        with:
          channel: 'stable'
      - name: Install Linux requirements
        run: sudo apt-get install clang cmake ninja-build pkg-config libgtk-3-dev
      - name: Build
        working-directory: packages/isar_inspector
        run: |
          flutter config --enable-linux-desktop
          flutter build linux
      - name: AppImage
        uses: AppImageCrafters/build-appimage@v1
        working-directory: packages/isar_inspector/linux/appimage
        with:
          recipe: "AppImageBuilder.yml"
          env:
            VERSION: ${{ github.ref }}
      - name: Compress
        working-directory: packages/isar_inspector/linux/appimage
        run: zip -r -y inspector.zip *.AppImage
      - name: Upload binary
        uses: svenstaro/upload-release-action@v1-release
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: packages/isar_inspector/linux/appimage/inspector.zip
          asset_name: Isar Inspector Linux AppImage.zip
          tag: ${{ github.ref }}
