name: Build Inspector

on:
  push:
    tags:
      - '*'

jobs:
  build_and_upload_macos:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v1
    - uses: subosito/flutter-action@v1
      with:
        channel: 'stable'
    - name: Build
      working-directory: packages/isar_inspector
      run: |
        flutter config --enable-macos-desktop
        flutter build macos
    - name: Compress
      working-directory: packages/isar_inspector/build/macos/Build/Products/Release/
      run: zip -r -y inspector.zip "Isar Inspector.app"
    - name: Upload binary
      uses: svenstaro/upload-release-action@v1-release
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: packages/isar_inspector/build/macos/Build/Products/Release/inspector.zip
        asset_name: Isar Inspector MacOS.zip
        tag: ${{ github.ref }}

  build_and_upload_linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: subosito/flutter-action@v1
        with:
          channel: 'stable'
      - name: Install Linux requirements
        run: |
          sudo apt-get install clang cmake ninja-build pkg-config libgtk-3-dev
          sudo apt-get install -y python3-pip python3-setuptools patchelf desktop-file-utils libgdk-pixbuf2.0-dev fakeroot strace fuse
          sudo wget https://github.com/AppImage/AppImageKit/releases/download/continuous/appimagetool-x86_64.AppImage -O /usr/local/bin/appimagetool
          sudo chmod +x /usr/local/bin/appimagetool
          sudo pip3 install appimage-builder
      - name: Build
        working-directory: packages/isar_inspector
        run: |
          flutter config --enable-linux-desktop
          flutter build linux
      - name: AppImage
        working-directory: packages/isar_inspector/linux/appimage
        run: VERSION=${{ github.ref }}; appimage-builder --recipe AppImageBuilder.yml
      - name: Compress
        working-directory: packages/isar_inspector/linux/appimage
        run: zip -r -y inspector.zip *.AppImage
      - name: Upload binary
        uses: svenstaro/upload-release-action@v1-release
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: packages/isar_inspector/linux/appimage/inspector.zip
          asset_name: Isar Inspector Linux AppImage.zip
          tag: ${{ github.ref }}
