name: Build Inspector

on:
  push:
    tags:
      - "*"

jobs:
  build_and_upload:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: subosito/flutter-action@v2
      - name: Build
        working-directory: packages/isar_inspector
        run: flutter build web
      - name: Deploy to GitHub Pages
        uses: crazy-max/ghaction-github-pages@v2
        with:
          target_branch: gh-pages
          fqdn: inspect.isar.dev
          build_dir: packages/isar_inspector/build/web
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}