name: Build Inspector

on:
  push:
    tags:
      - '*'

jobs:
  build_and_upload:
    strategy:
      matrix:
        args: 
          - os: macos-latest
            build: macos
          - os: ubuntu-latest
            build: linux
    runs-on: ${{ matrix.args.os }}
    steps:
      - uses: actions/checkout@v1
      - uses: subosito/flutter-action@v1
        with:
          channel: 'stable'
      - name: Install Linux requirements
        run: sudo apt-get install clang cmake ninja-build pkg-config libgtk-3-dev
        if: matrix.args.os == 'ubuntu-latest'
      - name: Build
        working-directory: packages/isar_inspector
        run: |
          flutter config --enable-${{ matrix.args.build }}-desktop
          flutter build ${{ matrix.args.build }}
      - name: Compress
        working-directory: packages/isar_inspector/build/${{ matrix.args.build }}/Build/Products/Release/
        run: zip -r -y inspector.zip "isar_inspector"
      - name: Upload binary
        uses: svenstaro/upload-release-action@v1-release
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: packages/isar_inspector/build/${{ matrix.args.build }}/Build/Products/Release/inspector.zip
          asset_name: Isar Inspector ${{ matrix.args.build }}.zip
          tag: ${{ github.ref }}
