name: Build Inspector

on:
  push:
    tags:
      - '*'

jobs:
  build_and_upload_macos:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v1
    - uses: subosito/flutter-action@v1
      with:
        channel: 'stable'
    - name: Build
      working-directory: packages/isar_inspector
      run: |
        flutter config --enable-macos-desktop
        flutter build macos
    - name: Compress
      working-directory: packages/isar_inspector/build/macos/Build/Products/Release/
      run: zip -r -y inspector.zip "Isar Inspector.app"
    - name: Upload binary
      uses: svenstaro/upload-release-action@v1-release
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: packages/isar_inspector/build/macos/Build/Products/Release/inspector.zip
        asset_name: Isar_Inspector_MacOS.zip
        tag: ${{ github.ref }}

  build_and_upload_linux:
    runs-on: ubuntu-latest
    container:
      image: bilelmoussaoui/flatpak-github-actions:gnome-40
      options: --privileged
    steps:
      - name: Install Linux requirements
        run: |
          sudo dnf install -y tar clang cmake ninja-build pkg-config gtk3-devel
      - uses: actions/checkout@v1
      - uses: subosito/flutter-action@v1
        with:
          channel: 'stable'
      - name: Build
        working-directory: packages/isar_inspector
        run: |
          flutter config --enable-linux-desktop
          flutter build linux
      - name: Compress Tar
        working-directory: packages/isar_inspector/linux/flatpak
        run: ./build-tar.sh
      - name: Flatpak
        working-directory: packages/isar_inspector/linux/flatpak
        run: ./build-flatpak.sh
      - name: Upload flatpak
        uses: svenstaro/upload-release-action@v1-release
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: packages/isar_inspector/linux/flatpak/app.flatpak
          asset_name: Isar_Inspector_Linux.flatpak
          tag: ${{ github.ref }}
