name: Isar test release

on: push

jobs:
  build_binaries:
    name: Build Binaries
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-18.04 # use older linux for glibc compatibility see #288
            artifact_name: libisar_linux_arm64.so
            script: build_linux.sh arm64
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - name: Prepare Build
        uses: ./.github/actions/prepare-build
      - name: Set env
        run: echo "ISAR_VERSION=${{ github.ref_name }}" >> $GITHUB_ENV
      - name: Build binary
        run: bash tool/${{ matrix.script }}
