name: Dart CI

on: [push, pull_request]

jobs:
  test:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v2
      - uses: subosito/flutter-action@v1
        with:
          channel: 'stable'

      - name: Run isar_generator
        run: |
          flutter pub get
          flutter pub run build_runner build
        working-directory: packages/isar_test
        
      - name: Download binaries
        run: bash tool/setup_tests.sh
        working-directory: packages/isar_test
      
      - name: Run tests
        run: flutter test
        working-directory: packages/isar_test
  

  drive_ios:
    strategy:
      matrix:
        device:
          - "iPhone 8 (14.4)"
          - "iPhone 11 Pro Max (14.4)"
      fail-fast: false

    runs-on: macos-latest
    steps:
      - name: "List all simulators"
        run: "xcrun instruments -s"
      - name: "Start Simulator"
        run: |
          UDID=$(
            xcrun instruments -s |
            awk \
              -F ' *[][]' \
              -v 'device=${{ matrix.device }}' \
              '$1 == device { print $2 }'
          )
          xcrun simctl boot "${UDID:?No Simulator with this name found}"

      - uses: actions/checkout@v1
      - uses: subosito/flutter-action@v1
        with:
          channel: 'stable'

      - name: Run isar_generator
        run: |
          flutter pub get
          flutter pub run build_runner build
        working-directory: packages/isar_test

      - name: Download binaries
        run: bash tool/download_binaries.sh
        working-directory: packages/isar_flutter_libs

      - name: "Run Flutter Driver tests"
        run: "flutter drive --driver=test_driver/isar_test.dart --target=test_driver/isar.dart"
        working-directory: packages/isar_test
        
        
  drive_android:
    runs-on: macos-latest
    strategy:
      matrix:
        api-level: [29] #[21, 29]
        target: [default]
      fail-fast: false

    steps:
      - uses: actions/checkout@v1
      - uses: subosito/flutter-action@v1
        with:
          channel: 'stable'

      - name: Run isar_generator
        run: |
          flutter pub get
          flutter pub run build_runner build
        working-directory: packages/isar_test

      - name: Download binaries
        run: bash tool/download_binaries.sh
        working-directory: packages/isar_flutter_libs

      - name: "Run Flutter Driver tests"
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: ${{ matrix.api-level }}
          target: ${{ matrix.target }}
          arch: x86_64
          profile: Nexus 6
          working-directory: packages/isar_test
          script: "flutter drive --driver=test_driver/isar_test.dart --target=test_driver/isar.dart"
