name: Dart CI

on: [push, pull_request]

jobs:
  drive_ios:
    strategy:
      matrix:
        device:
          - "iPhone 8"
          - "iPhone 11 Pro Max"
      fail-fast: false
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - name: Start simulator
        uses: futureware-tech/simulator-action@v1
        with:
          model: ${{ matrix.device }}
      - uses: subosito/flutter-action@v1
        with:
          channel: 'stable'
      - name: Download binaries
        run: bash tool/download_binaries.sh
        working-directory: packages/isar_flutter_libs
      - name: Run Flutter Driver tests
        run: |
          flutter pub get
          flutter pub run build_runner build
          flutter drive --driver=test_driver/isar_test.dart --target=test_driver/isar.dart
        working-directory: packages/isar_test
        
  drive_android:
    runs-on: macos-latest
    strategy:
      matrix:
        api-level: [29] #[21, 29]
        target: [default]
      fail-fast: false
    steps:
      - uses: actions/checkout@v2
      - uses: subosito/flutter-action@v1
        with:
          channel: 'stable'
      - name: Run isar_generator
        run: |
          flutter pub get
          flutter pub run build_runner build
        working-directory: packages/isar_test
      - name: Download binaries
        run: bash tool/download_binaries.sh
        working-directory: packages/isar_flutter_libs
      - name: Run Flutter Driver tests
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: ${{ matrix.api-level }}
          target: ${{ matrix.target }}
          arch: x86_64
          profile: Nexus 6
          working-directory: packages/isar_test
          script: "flutter drive --driver=test_driver/isar_test.dart --target=test_driver/isar.dart"
  
  drive_desktop:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
      fail-fast: false
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - uses: subosito/flutter-action@v1
        with:
          channel: 'stable'
      - name: Install Linux requirements
        run: sudo apt-get install clang cmake ninja-build pkg-config libgtk-3-dev
        if: matrix.os == 'ubuntu-latest'
      - name: Download binaries
        run: bash tool/download_binaries.sh
        working-directory: packages/isar_flutter_libs
      - name: Run Flutter Driver tests
        run: |
          flutter pub get
          flutter pub run build_runner build
          flutter config --no-enable-web
          flutter config --enable-macos-desktop 
          flutter config --enable-linux-desktop 
          flutter config --enable-windows-desktop 
          flutter drive --driver=test_driver/isar_test.dart --target=test_driver/isar.dart
        working-directory: packages/isar_test

  test_multi:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: subosito/flutter-action@v1
        with:
          channel: 'stable'
      - name: Run child1 isar_generator
        run: |
          dart pub get
          dart pub run build_runner build
        working-directory: packages/isar_test_multi/child_package1
      - name: Run child2 isar_generator
        run: |
          dart pub get
          dart pub run build_runner build
        working-directory: packages/isar_test_multi/child_package2
      - name: Run isar_generator
        run: |
          flutter pub get
          flutter pub run build_runner build
        working-directory: packages/isar_test_multi/root_package
      - name: Download binaries
        run: bash tool/setup_tests.sh
        working-directory: packages/isar_test_multi/root_package
      - name: Run tests
        run: flutter test
        working-directory: packages/isar_test_multi/root_package